apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: theia
  namespace: ralphilius
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: theia-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Eclipse Theia'
spec:
  rules:
  - host: theia-ralphilius.cloud.okteto.net
    http:
      paths:
      - backend:
          serviceName: theia
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: theia
 namespace: ralphilius
spec:
 ports:
 - port: 80
   name: "80"
   targetPort: 3000
 - port: 3001
   name: "3001"
   targetPort: 3001
 selector:
   app: theia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theia
  name: theia
  namespace: ralphilius
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - image: theiaide/theia-full:latest
        imagePullPolicy: Always
        name: theia
        ports:
        - containerPort: 3000
